
export type Project = {
  id: string,
  name: string,
  stack: string[],
  teamSize: number,
  role: string,
  description: string,
  type: string,
  dateFrom: string,
  dateTo: string | null,
  link: string | null,
  github: string | null,
  isAvaible: boolean,
}

export const MOCK_PROJECTS: Project[] = [
  {
    id: "My Portfolio Angular",
    name: "My Portfolio Angular",
    stack: [
      "Angular",
      "Tailwind",
      "SonarCloud",
      "Figma",
    ],
    link: "https://giaspa.github.io/my-portfolio-angular/",
    github: "https://github.com/Giaspa/my-portfolio-angular",
    isAvaible: true,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ipsum nemo asperiores necessitatibus corrupti? Iste nulla velit enim modi alias fugiat culpa, dolor aut fuga porro! Eos doloribus atque ducimus.",
    type: "",
    dateFrom: "Nov 2024",
    dateTo: null,
    teamSize: 1,
    role: "Frontend developer & UX/UI designer"
  },
  {
    id: "My Next Docs",
    name: "My Next Docs",
    stack: [
      "React",
      "Next",
      "Tailwind",
      "TypeScript",
    ],
    link: null,
    github: "https://github.com/Giaspa/my-next-docs",
    isAvaible: true,
    description: "",
    type: "",
    dateFrom: "Nov 2024",
    dateTo: null,
    teamSize: 1,
    role: "Fullstack developer"
  },
  {
    id: "The Guild",
    name: "The Guild",
    stack: [
      "React",
      "Next",
      "Supabase",
      "Prisma",
      "Tailwind",
      "TypeScript",
      "Figma",
    ],
    link: null,
    github: null,
    isAvaible: false,
    description: "",
    type: "",
    dateFrom: "Nov 2024",
    dateTo: null,
    teamSize: 2,
    role: "Frontend developer & UX/UI designer"
  },
  {
    id: "My Angular Docs",
    name: "My Angular Docs",
    stack: [
      "Angular",
      "Tailwind",
      "SonarCloud",
    ],
    link: "https://giaspa.github.io/my-angular-docs/",
    github: "https://github.com/Giaspa/my-angular-docs",
    isAvaible: true,
    description: "",
    type: "",
    dateFrom: "Oct 2024",
    dateTo: "Nov 2024",
    teamSize: 1,
    role: "Frontend developer"
  },
  {
    id: "Interfinder",
    name: "Interfinder",
    stack: [
      "Svelte",
      "Tailwind",
      "TypeScript",
    ],
    link: null,
    github: null,
    isAvaible: false,
    description: "",
    type: "",
    dateFrom: "Oct 2024",
    dateTo: null,
    teamSize: 3,
    role: "Frontend developer"
  },
  {
    id: "CT Servizi",
    name: "CT Servizi",
    stack: [
      "React",
      "Redux",
      "Tailwind",
      "Vite",
      "TypeScript",
      "Figma",
    ],
    link: null,
    github: null,
    isAvaible: false,
    description: "",
    type: "",
    dateFrom: "Ago 2024",
    dateTo: "Oct 2024",
    teamSize: 3,
    role: "Frontend developer & UX/UI designer"
  },
  {
    id: "ALD Ayvens",
    name: "ALD Ayvens",
    stack: [
      "Angular",
      "Javascript",
    ],
    link: null,
    github: null,
    isAvaible: false,
    description: "",
    type: "",
    dateFrom: "Feb 2024",
    dateTo: "Ago 2024",
    teamSize: 22,
    role: "Frontend developer"
  },
  {
    id: "SWEN - funds manager",
    name: "SWEN - funds manager",
    stack: [
      "React",
      "Sass",
      "TypeScript",
      "Figma",
    ],
    link: null,
    github: null,
    isAvaible: false,
    description: "",
    type: "",
    dateFrom: "Jan 2024",
    dateTo: "Feb 2024",
    teamSize: 1,
    role: "Fullstack developer & UX/UI designer"
  },
  {
    id: "Game of life",
    name: "Game of life",
    stack: [
      "Angular",
      "Sass",
      "Figma",
    ],
    link: "https://giaspa.github.io/game-of-life/",
    github: "https://github.com/Giaspa/game-of-life",
    isAvaible: true,
    description: "",
    type: "",
    dateFrom: "Nov 2023",
    dateTo: "Jan 2024",
    teamSize: 1,
    role: "Frontend developer & UX/UI designer"
  },
  {
    id: "Gestione Fondi Formatemp",
    name: "Gestione Fondi Formatemp",
    stack: [
      "Angular",
      "Figma",
      "Miro",
    ],
    link: "https://ftweb.formatemp.it/#/",
    github: null,
    isAvaible: true,
    description: "",
    type: "",
    dateFrom: "Jun 2023",
    dateTo: "Mar 2024",
    teamSize: 6,
    role: "Frontend developer, Team leader & UX/UI designer"
  },
  {
    id: "La Tomba di Eracle - rpg game",
    name: "La Tomba di Eracle - rpg game",
    stack: [
      "Angular",
      "Firebase",
      "Figma",
    ],
    link: null,
    github: null,
    isAvaible: false,
    description: "In my role, I've had the opportunity to create over 80 components using the latest technologies such as Angular 14, HTML, CSS, and Typescript, which has allowed me to build robust and dynamic user interfaces. I've also taken the initiative to implement a Rest API utilizing Google Authentication, Google Spreadsheets, and Firebase Realtime Database, enhancing the functionality and interactivity of our projects. To ensure seamless accessibility, I've deployed these projects on Firebase hosting, providing users with a fast and reliable platform. I'm dedicated to staying at the forefront of technology and delivering cutting-edge solutions in all my endeavors.",
    type: "",
    dateFrom: "Dec 2021",
    dateTo: "Jul 2023",
    teamSize: 2,
    role: "Fullstack developer & UX/UI designer"

  },
  {
    id: "Repubblica digitale",
    name: "Repubblica digitale",
    stack: [
      "Angular",
      "MongoDB",
      "Sass",
      "Figma",
    ],
    link: "https://repubblicadigitale.gov.it/portale/",
    github: null,
    isAvaible: true,
    description: "",
    type: "",
    dateFrom: "Jan 2023",
    dateTo: "Jun 2023",
    teamSize: 6,
    role: "Frontend developer, Team leader & UX/UI designer"
  },
  {
    id: "RVE - Regione Veneto",
    name: "RVE - Regione Veneto",
    stack: [
      "Angular",
      "Java",
      "Spring",
      "Figma",
    ],
    link: "https://www.regione.veneto.it/web/guest/home",
    github: null,
    isAvaible: true,
    description: "As a leader, I've had the privilege of leading a team of five talented individuals, providing guidance and direction in the development of the project's frontend components. Together, we've worked diligently to ensure the frontend aspects meet the highest standards of quality and user experience. I've personally written and managed over 8,000 lines of code using a modern tech stack, including Angular 15, HTML, SCSS, and Typescript. This commitment to code quality has been essential in delivering a robust and feature-rich application. Additionally, I've undertaken the task of re-engineering the codebase to implement crucial features such as accessibility and responsiveness. These improvements have not only enhanced the project's usability but have also made it more inclusive and adaptable to different devices and user needs. I'm dedicated to achieving excellence in every project I undertake and am committed to delivering exceptional results.",
    type: "",
    dateFrom: "Apr 2022",
    dateTo: "Jan 2023",
    teamSize: 6,
    role: "Fullstack developer, Team leader & UX/UI designer"
  },
  {
    id: "Biobanca Nazionale - IZS",
    name: "Biobanca Nazionale - IZS",
    stack: [
      "Angular",
      "Java",
      "Spring",
      "MySql",
      "MyBatis",
    ],
    link: null,
    github: null,
    isAvaible: false,
    description: "In my role, I've been responsible for maintaining over 40 components using Angular 12, HTML, CSS, and Typescript, ensuring the seamless operation of our projects. As a team leader, I've had the privilege of leading a team of four talented individuals in the development and maintenance of our project, covering both the backend and frontend aspects. This collaborative effort has been instrumental in our success. One of the significant contributions I made was the introduction of a QR code generator, which greatly accelerated the research process, making it more efficient and user-friendly. It's been an exciting journey, and I'm committed to continually improving and innovating in the projects I'm involved in.",
    type: "",
    dateFrom: "Jan 2021",
    dateTo: "Jun 2023",
    teamSize: 7,
    role: "Fullstack developer & Team leader"
  },
]
